import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const listings = [
  { id:1,image:'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85',price:895000,beds:4,baths:3,sqft:2640,type:'Single Family',city:'Austin, TX',address:'1804 Westlake Dr',featured:true },
  { id:2,image:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=85',price:1245000,beds:3,baths:2.5,sqft:2110,type:'Condo',city:'Miami, FL',address:'285 Biscayne Blvd',featured:true },
  { id:3,image:'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=85',price:749000,beds:3,baths:2,sqft:1980,type:'Townhouse',city:'Charlotte, NC',address:'912 Queens Rd',featured:false },
  { id:4,image:'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1200&q=85',price:2095000,beds:5,baths:4,sqft:4350,type:'Single Family',city:'Scottsdale, AZ',address:'7442 N Sunset Blvd',featured:true },
  { id:5,image:'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1200&q=85',price:589000,beds:2,baths:2,sqft:1240,type:'Condo',city:'Denver, CO',address:'1550 Larimer St',featured:false },
  { id:6,image:'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=85',price:1650000,beds:4,baths:3.5,sqft:3120,type:'Single Family',city:'Nashville, TN',address:'4211 Belle Meade Blvd',featured:false },
  { id:7,image:'https://images.unsplash.com/photo-1605146769289-440113cc3d00?auto=format&fit=crop&w=1200&q=85',price:429000,beds:3,baths:2,sqft:1740,type:'Single Family',city:'Phoenix, AZ',address:'2217 E Camelback Rd',featured:false },
  { id:8,image:'https://images.unsplash.com/photo-1600585153490-76fb20a32601?auto=format&fit=crop&w=1200&q=85',price:3250,beds:2,baths:2,sqft:1180,type:'Apartment',city:'Chicago, IL',address:'111 W Grand Ave',featured:false,rent:true },
  { id:9,image:'https://images.unsplash.com/photo-1600047508788-786a9b8a7e36?auto=format&fit=crop&w=1200&q=85',price:4200,beds:3,baths:2,sqft:1550,type:'Apartment',city:'Seattle, WA',address:'908 Pine St',featured:false,rent:true }
];
const cities=['Austin, TX','Miami, FL','New York, NY','Los Angeles, CA','Denver, CO','Nashville, TN'];
const money=n=>n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});

function Modal({title,onClose,children}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><button className="modal-close" onClick={onClose}>×</button><h2>{title}</h2>{children}</div></div>}

function SearchBar({mode,setMode,onSearch}){
 const [location,setLocation]=useState(''); const [type,setType]=useState('Any home type'); const [beds,setBeds]=useState('Any beds'); const [price,setPrice]=useState('Any price');
 const submit=e=>{e.preventDefault();onSearch({location,type,beds,price})};
 return <form className="search-panel" onSubmit={submit}><div className="mode-tabs">{['Buy','Rent'].map(x=><button type="button" key={x} className={mode===x?'active':''} onClick={()=>setMode(x)}>{x}</button>)}</div><div className="search-fields"><label><span>Location</span><input value={location} onChange={e=>setLocation(e.target.value)} placeholder="City, ZIP or neighborhood" /></label><label><span>Price</span><select value={price} onChange={e=>setPrice(e.target.value)}><option>Any price</option><option>Under $500k</option><option>$500k - $1M</option><option>$1M - $2M</option><option>$2M+</option></select></label><label><span>Home type</span><select value={type} onChange={e=>setType(e.target.value)}><option>Any home type</option><option>Single Family</option><option>Condo</option><option>Townhouse</option><option>Apartment</option></select></label><label><span>Beds</span><select value={beds} onChange={e=>setBeds(e.target.value)}><option>Any beds</option><option>1+</option><option>2+</option><option>3+</option><option>4+</option></select></label><button className="search-button">Search homes</button></div></form>
}

function ListingCard({listing,onOpen}){const [saved,setSaved]=useState(false);return <article className="card" onClick={()=>onOpen(listing)}><div className="image-wrap"><img src={listing.image} alt={listing.address}/><button className={saved?'save saved':'save'} onClick={e=>{e.stopPropagation();setSaved(!saved)}} aria-label="Save listing">{saved?'♥':'♡'}</button>{listing.featured&&<span className="tag">Featured</span>}</div><div className="card-body"><div className="price-row"><h3>{listing.rent?money(listing.price)+' / mo':money(listing.price)}</h3><span>{listing.type}</span></div><p className="facts"><b>{listing.beds}</b> bd <b>{listing.baths}</b> ba <b>{listing.sqft.toLocaleString()}</b> sqft</p><p className="address">{listing.address}, {listing.city}</p><p className="meta">Listed on PropertyAdviser</p></div></article>}

function App(){
 const [mode,setMode]=useState('Buy'); const [query,setQuery]=useState({location:'',type:'Any home type',beds:'Any beds',price:'Any price'}); const [modal,setModal]=useState(null); const [selected,setSelected]=useState(null); const [email,setEmail]=useState(''); const [message,setMessage]=useState('');
 const results=useMemo(()=>listings.filter(l=>{if(mode==='Rent'&&!l.rent)return false;if(mode==='Buy'&&l.rent)return false;const loc=query.location.toLowerCase();if(loc&&!(`${l.city} ${l.address}`).toLowerCase().includes(loc))return false;if(query.type!=='Any home type'&&l.type!==query.type)return false;if(query.beds!=='Any beds'&&l.beds<Number(query.beds[0]))return false;if(mode==='Buy'){if(query.price==='Under $500k'&&l.price>=500000)return false;if(query.price==='$500k - $1M'&&(l.price<500000||l.price>1000000))return false;if(query.price==='$1M - $2M'&&(l.price<1000000||l.price>2000000))return false;if(query.price==='$2M+'&&l.price<2000000)return false}return true}),[mode,query]);
 const openResults=filters=>{setQuery(filters);document.getElementById('results')?.scrollIntoView({behavior:'smooth'})};
 const submitEmail=e=>{e.preventDefault();if(email){setMessage('Thanks. You are on the PropertyAdviser list.');setEmail('')}};
 return <>
 <header className="header"><div className="container nav"><a className="brand" href="#top">Property<span>Adviser</span><small>.com</small></a><nav><a href="#results">Buy</a><a href="#results" onClick={()=>setMode('Rent')}>Rent</a><a href="#sell">Sell</a><a href="#mortgage">Mortgage</a><a href="#resources">Resources</a></nav><div className="nav-actions"><button className="link-btn" onClick={()=>setModal('signin')}>Sign in</button><button className="outline-btn" onClick={()=>setModal('list')}>List a property</button></div></div></header>
 <main id="top"><section className="hero"><div className="hero-bg"/><div className="container hero-inner"><div className="hero-copy"><span className="eyebrow">REAL ESTATE, MADE SIMPLE</span><h1>Find a place that feels like <em>home.</em></h1><p>Explore homes, apartments and investment properties across the United States.</p></div><SearchBar mode={mode} setMode={setMode} onSearch={openResults}/></div></section>
 <section className="trust"><div className="container trust-row"><span>Trusted by home seekers across the U.S.</span><div><b>1.2M+</b><small>Listings discovered</small></div><div><b>48</b><small>States covered</small></div><div><b>98%</b><small>Search satisfaction</small></div></div></section>
 <section className="section" id="results"><div className="container"><div className="section-heading"><div><span className="eyebrow">{mode==='Rent'?'RENTAL HOMES':'CURATED FOR YOU'}</span><h2>{query.location?`Homes near ${query.location}`:'Featured homes'}</h2><p>{results.length} properties match your current search.</p></div><button className="text-button" onClick={()=>setQuery({location:'',type:'Any home type',beds:'Any beds',price:'Any price'})}>Clear filters</button></div>{results.length?<div className="grid">{results.map(l=><ListingCard key={l.id} listing={l} onOpen={setSelected}/>)}</div>:<div className="empty"><h3>No homes found</h3><p>Try a broader city, home type or price range.</p></div>}</div></section>
 <section className="section light"><div className="container"><div className="section-heading"><div><span className="eyebrow">EXPLORE MARKETS</span><h2>Popular places to live</h2><p>Start your next search in a city people love.</p></div></div><div className="city-grid">{cities.map((city,i)=><a href="#results" className="city" key={city} onClick={()=>{setMode('Buy');setQuery({...query,location:city})}}><img src={listings[i%listings.length].image} alt={city}/><div><strong>{city}</strong><span>Explore homes →</span></div></a>)}</div></div></section>
 <section className="cta" id="sell"><div className="container cta-inner"><div><span className="eyebrow">SELL WITH CONFIDENCE</span><h2>Thinking about selling?</h2><p>Understand your local market, reach qualified buyers and get more from your next move.</p></div><button onClick={()=>setModal('valuation')}>Get a home value estimate <span>→</span></button></div></section>
 <section className="section" id="mortgage"><div className="container mortgage"><div><span className="eyebrow">MORTGAGE PLANNER</span><h2>Know your monthly payment before you shop.</h2><p>Use an illustrative estimate to understand principal, interest, taxes and insurance.</p></div><Mortgage/></div></section>
 <section className="section" id="resources"><div className="container resource-grid"><div><span className="eyebrow">PROPERTYADVISER GUIDES</span><h2>Make the next move with confidence.</h2><p>Practical insights for buying, renting, selling and investing in real estate.</p></div><div className="resource-list"><a href="#mortgage"><span>01</span><div><strong>First-time buyer guide</strong><p>What to know before you make an offer.</p></div><b>→</b></a><a href="#mortgage"><span>02</span><div><strong>Mortgage basics</strong><p>Understand rates, payments and affordability.</p></div><b>→</b></a><a href="#results"><span>03</span><div><strong>Investing in property</strong><p>Compare markets and build a smarter strategy.</p></div><b>→</b></a></div></div></section>
 </main><footer><div className="container footer-grid"><div><a className="brand" href="#top">Property<span>Adviser</span><small>.com</small></a><p>Your guide to real estate across America.</p></div><div><strong>Explore</strong><a href="#results">Buy</a><a href="#results" onClick={()=>setMode('Rent')}>Rent</a><a href="#sell">Sell</a><a href="#mortgage">Mortgage</a></div><div><strong>Company</strong><a href="#resources">About</a><a href="#resources">How it works</a><a href="#sell">Contact</a><a href="#resources">Privacy</a></div><div><strong>Stay informed</strong><p>Market insights and useful property tips.</p><form className="subscribe" onSubmit={submitEmail}><input aria-label="Email address" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email address" type="email" required/><button>→</button></form>{message&&<small className="success">{message}</small>}</div></div><div className="container copyright"><span>© 2026 PropertyAdviser.com. Demo project.</span><span>Built for the U.S. market.</span></div></footer>
 {selected&&<Modal title={selected.address} onClose={()=>setSelected(null)}><img className="modal-image" src={selected.image} alt={selected.address}/><div className="detail-top"><strong>{selected.rent?money(selected.price)+' / month':money(selected.price)}</strong><span>{selected.city}</span></div><p>{selected.beds} bedrooms · {selected.baths} bathrooms · {selected.sqft.toLocaleString()} sqft · {selected.type}</p><p className="muted">This demo listing is for the PropertyAdviser.com prototype. Listing data can later be connected to MLS/IDX or another licensed feed.</p><button className="primary wide" onClick={()=>setModal('contact')}>Contact listing agent</button></Modal>}
 {modal==='signin'&&<Modal title="Welcome back" onClose={()=>setModal(null)}><form className="form" onSubmit={e=>{e.preventDefault();setMessage('Demo sign-in submitted.');setModal(null)}}><input type="email" placeholder="Email address" required/><input type="password" placeholder="Password" required/><button className="primary">Sign in</button><p className="muted">Demo only. Authentication is ready to connect to a real backend.</p></form></Modal>}
 {modal==='list'&&<Modal title="List your property" onClose={()=>setModal(null)}><form className="form" onSubmit={e=>{e.preventDefault();setMessage('Your listing request has been received.');setModal(null)}}><input placeholder="Property address" required/><input placeholder="Your name" required/><input type="email" placeholder="Email address" required/><select required><option value="">Property type</option><option>Single Family</option><option>Condo</option><option>Townhouse</option><option>Multi-family</option></select><button className="primary">Start listing</button></form></Modal>}
 {modal==='valuation'&&<Modal title="Get a home value estimate" onClose={()=>setModal(null)}><form className="form" onSubmit={e=>{e.preventDefault();setMessage('Valuation request submitted.');setModal(null)}}><input placeholder="Property address" required/><input placeholder="ZIP code" required/><input type="email" placeholder="Email address" required/><button className="primary">Request estimate</button></form></Modal>}
 {modal==='contact'&&<Modal title="Contact listing agent" onClose={()=>setModal(null)}><form className="form" onSubmit={e=>{e.preventDefault();setMessage('Your enquiry has been sent.');setModal(null)}}><input placeholder="Your name" required/><input type="email" placeholder="Email address" required/><textarea placeholder="I am interested in this property..." rows="5" required/><button className="primary">Send enquiry</button></form></Modal>}
 </>;
}
function Mortgage(){const [price,setPrice]=useState(600000);const [down,setDown]=useState(20);const [rate,setRate]=useState(6.5);const [years,setYears]=useState(30);const loan=price*(1-down/100);const r=rate/100/12,n=years*12;const payment=r?loan*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1):loan/n;return <div className="mortgage-box"><label>Home price <b>{money(price)}</b><input type="range" min="150000" max="2500000" step="10000" value={price} onChange={e=>setPrice(+e.target.value)}/></label><label>Down payment <b>{down}%</b><input type="range" min="0" max="60" value={down} onChange={e=>setDown(+e.target.value)}/></label><label>Interest rate <b>{rate.toFixed(2)}%</b><input type="range" min="3" max="10" step=".05" value={rate} onChange={e=>setRate(+e.target.value)}/></label><label>Loan term <select value={years} onChange={e=>setYears(+e.target.value)}><option value="30">30 years</option><option value="20">20 years</option><option value="15">15 years</option></select></label><div className="payment"><span>Estimated principal & interest</span><strong>{money(payment)}<small>/mo</small></strong><em>Taxes, insurance, HOA and other costs are not included.</em></div></div>}

createRoot(document.getElementById('root')).render(<App/>);
